AWSTemplateFormatVersion: 2010-09-09
Description: >
    Author: Bongani Mokase
    Email: bonganimokae@gmail.com
    Project: Deploying a High-Availabilty Web App using CloudFormation
Parameters:
  # Paramenters to be used
 
Resources:
  # Instance profile contains the IAM Role name(s) that we want to associate to our auto scaling EC2 Servers
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - UdacityS3ReadOnlyEC2
Outputs: 
  # This is also optional.
  
# Sample UserData
# When creating your Launch Configuration, you may need a UserData script
# here's one that you can use for Ubuntu Linux that will:
# Install Apache Web Server, Start it, and create an index.html that will be displayed
# when you visit the IP address of this server with your web browser
#Here it is:
#
#          #!/bin/bash
#          apt-get update -y
#          apt-get install apache2 -y
#          systemctl start apache2.service
#          cd /var/www/html
#          echo "Udacity Demo Web Server Up and Running!" > index.html